import { randomBytes } from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { inboxUrlOf, loadConfig } from '../config.js';
import { migrate, openDb } from '../db/index.js';
import { IdentityService } from '../identity/service.js';
import { encodeContactCode } from '../lib/contact-code.js';

export interface InitOptions {
  publicUrl?: string;
  displayName?: string;
  port?: number;
  dev?: boolean;
  force?: boolean;
  apiToken?: string;
}

function envTemplate(args: {
  publicUrl: string;
  port: number;
  masterKey: string;
  displayName: string;
  apiToken?: string;
  insecure: boolean;
}): string {
  return `# Generated by \`a2a init\` — keep this file private.
PUBLIC_BASE_URL=${args.publicUrl}
DISPLAY_NAME=${args.displayName}

# 32-byte master key (base64). Seals private keys at rest. NEVER share.
AGENT_MASTER_KEY=${args.masterKey}

PORT=${args.port}
HOST=0.0.0.0
LOG_LEVEL=info

# Set to true ONLY when communicating with peers over plaintext HTTP.
# Production with real peers MUST be HTTPS.
ALLOW_INSECURE_HTTP=${args.insecure ? 'true' : 'false'}
${args.apiToken ? `\n# Bearer token to allow non-loopback access to /api.\nAPI_TOKEN=${args.apiToken}\n` : ''}`;
}

export async function cliInit(opts: InitOptions): Promise<void> {
  const envPath = path.resolve(process.cwd(), '.env');
  if (fs.existsSync(envPath) && !opts.force) {
    console.error(`.env already exists at ${envPath}. Pass --force to overwrite.`);
    process.exit(2);
  }

  const port = opts.port ?? 4242;
  const dev = !!opts.dev;
  const publicUrl = opts.publicUrl ?? (dev ? `http://127.0.0.1:${port}` : '');
  if (!publicUrl) {
    console.error(
      'Provide --public-url <https://your.host> (the URL peers will use to reach your inbox),\n' +
        'or pass --dev to default to http://127.0.0.1:<port> for local testing.',
    );
    process.exit(2);
  }

  const masterKey = randomBytes(32).toString('base64');
  fs.writeFileSync(
    envPath,
    envTemplate({
      publicUrl,
      port,
      masterKey,
      displayName: opts.displayName ?? 'agent',
      apiToken: opts.apiToken,
      insecure: dev,
    }),
    { mode: 0o600 },
  );

  // Bootstrap DB + identity.
  const config = loadConfig({ envPath });
  const db = openDb(config.dbPath);
  migrate(db);
  const identity = new IdentityService(db, config).ensureLocalIdentity(config.displayName);
  db.close();

  const inbox = inboxUrlOf(config);
  const code = encodeContactCode({ pubkey: identity.pubkey, endpointUrl: inbox });

  console.log(`wrote ${envPath} (chmod 600)`);
  console.log(`display name:  ${config.displayName}`);
  console.log(`fingerprint:   ${identity.fingerprint}`);
  console.log(`inbox URL:     ${inbox}`);
  console.log(`db:            ${config.dbPath}`);
  console.log('');
  console.log('Your contact code (share this with people you want to message):');
  console.log('');
  console.log(`  ${code}`);
  console.log('');
  console.log('Next: `pnpm dev` (or `node dist/index.js`) to start the server.');
}
